version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 1509:1509
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football